--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Clickedtran/GiftCode
build-by-default: true
branches:
- Master
projects:
  GiftCode:
    path: ""
    icon: icon.jpg
    libs:
      - src: dktaps-pm-pl/pmforms/pmforms
        version: ^2.1.0
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
...
