--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Clickedtran/GiftCode
build-by-default: true
branches:
- Master
projects:
  GiftCode:
    path: ""
    icon: icon.jpg
    libs:
      - src: AID-LEARNING/Commando/Commando
        version: ^3.1.0
        branch: pm5
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.1.3
        branch: pm5
      - src: VennDev/VFormOOPAPI/VFormOOPAPI
        version: ^2.2.3
        branch: "main"
      - src: VennDev/LibVapmPMMP/LibVapmPMMP
        version: ^1.8.8
        branch: "main"
...
